### ISSUE TITLE
Post => Comment => User possible to eager load?

### ISSUE THREAD

**Issue by mrrooijen** [flyerhzm/mongoid-eager-loading#4]
Hi. Just to throw out another idea to evaluate.

I was experimenting and I had this setup:

```
class User
  include Mongoid::Document
  references_many :posts
  references_many :comments
end

class Post
  include Mongoid::Document
  embeds_many :comments
end

class Comment
  include Mongoid::Document
  embedded_in :post, :inverse_of => :comments
  referenced_in :user
end
```

It doesn't work but maybe an idea to implement (if at all possible of course) in the future. I think it might be a little complex but who knows!

Basically what might be cool to be able to do is something like this (with the above setup).

```
# Something like this
Post.includes('comments.user').each do |post|
  post.comments.each do |comment|
    puts comment.user.name
  end
end

# Same thing as above, just different syntax in #includes()
Post.includes(:comments => :user).each do |post|
  post.comments.each do |comment|
    puts comment.user.name
  end
end
```

So basically that you can instruct a root-level document to eager-load the user of the embedded (Comment) document. This sounds quite complex and I have no idea whether that messes up the internals but nonetheless an interesting idea if at all possible. :)

**Comment by flyerhzm** [comment]
Yes, this is what I want to implement next step. It may be a bit complex, not should not be too difficult to implement.

**Comment by mrrooijen** [comment]
Awesome. All this should definitely be merged into Mongoid itself. It's really useful stuff.

**Comment by marcalc** [comment]
Definitely, must have. :)

Thanks for the help!

**Comment by zolzaya** [comment]
Any news?

**Comment by flyerhzm** [comment]
this repo is deprecated, please use mongoid includes method.
