### ISSUE TITLE
Broken references_many behavior?

### ISSUE THREAD

**Issue by nanodeath** [flyerhzm/mongoid-eager-loading#5]
Having some issue with a code snippet

```
class Foo
    references_many :bars
end
class Bar
    referenced_in :foo
end

Foo.all.each do |f|
    puts f.bars.first
end
```

works fine.

But when I do this:
    Foo.all.includes(:bars) do |f|
        puts f.bars.first
    end
I get something like `undefined method 'first' for #<Bar:1234>`.  It might be important that Foo right now only has one Bar associated with it, and also that I'm using mongoid 2.0.0.rc6 (though edge breaks too).  Thoughts?  sort of weird.

**Comment by flyerhzm** [comment]
I have tried to reproduce this issue, but failed. Check it here: https://github.com/flyerhzm/mongoid-eager-loading/commit/81d97cbfe69ae8f31b5a1c1834c757cfca417690. Could you do some hacks to see what's wrong?

**Comment by nanodeath** [comment]
Failing spec: https://github.com/nanodeath/mongoid-eager-loading/commit/80b11061407522a5121b05ccba3168b5d3bde563

**Comment by flyerhzm** [comment]
fixed, please try the edge codes, and let me know if it works

**Comment by nanodeath** [comment]
Works like a charm.  Not sure exactly what edge cases to test that aren't in the specs, but it Works For Me.  Down to 2 queries from 11.
